apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb
  namespace: demo
  labels:
    release: prometheus-stack
    app.kubernetes.io/name: mariadbs.kubedb.com
    app.kubernetes.io/instance: mariadb
spec:
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadbs.kubedb.com
      app.kubernetes.io/instance: mariadb
  endpoints:
  - port: metrics
    honorLabels: true
    interval: 30s
    path: /metrics
