apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
kind: Kustomization
patchesJson6902:
- path: patch.yaml
  target:
    group: kubedb.com
    kind: MongoDB
    name: sample-mongo
    namespace: demo
    version: v1alpha2
resources:
- gcs-repo.yaml
- sample-mongo-restore.yaml
