apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: mariadb-init
  namespace: demo
  labels:
    app.kubernetes.io/name: mariadbs.kubedb.com
    app.kubernetes.io/instance: mariadb
spec:
  task:
    name: mariadb-restore-10.5.8
  repository:
    name: mariadb-init-repo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mariadb
  rules:
    - snapshots: [latest]
