apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgreses.kubedb.com
  name: postgres-init
  namespace: demo
spec:
  repository:
    name: postgres-init-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: postgres
