apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: sample-mongo
    app.kubernetes.io/name: mongodbs.kubedb.com
    release: prometheus-stack
  name: sample-mongo-monitor
  namespace: demo
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: sample-mongo
      app.kubernetes.io/name: mongodbs.kubedb.com
