apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb-ui-server
  namespace: kubeops
spec:
  interval: 30m
  releaseName: kubedb-ui-server
  targetNamespace: kubedb
  chart:
    spec:
      chart: kubedb-ui-server
      version: "v2023.02.28"
      sourceRef:
        kind: HelmRepository
        name: kubedb
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
