apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb
  namespace: kubeops
spec:
  interval: 5m
  timeout: 10m
  releaseName: kubedb
  targetNamespace: kubedb
  chart:
    spec:
      chart: kubedb
      version: "v2023.02.28"
      sourceRef:
        kind: HelmRepository
        name: kubedb
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    kubedb-provisioner:
      enabled: true
    kubedb-ops-manager:
      enabled: true
    kubedb-autoscaler:
      enabled: true
    kubedb-schema-manager:
      enabled: true
    kubedb-dashboard:
      enabled: true
