apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: kubeops
spec:
  interval: 30m
  releaseName: grafana-operator
  chart:
    spec:
      chart: grafana-operator
      targetNamespace: monitoring
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
