apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kubeops
  labels:
    app.kubernetes.io/managed-by: kubeops.dev
    app.kubernetes.io/component: kube-prometheus-stack
    app.kubernetes.io/part-of: opscenter-monitoring
spec:
  interval: 30m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kubeops
