apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kubeops
spec:
  interval: 30m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      targetNamespace: monitoring
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kubeops
