apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring-config
  namespace: kubeops
spec:
  interval: 30m
  releaseName: monitoring-config
  targetNamespace: monitoring
  chart:
    spec:
      chart: monitoring-config
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: bytebuilders
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
