apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: panopticon
  namespace: kubeops
spec:
  interval: 5m
  timeout: 10m
  releaseName: panopticon
  targetNamespace: monitoring
  chart:
    spec:
      chart: panopticon
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
