apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: panopticon
  namespace: kubeops
  labels:
    app.kubernetes.io/managed-by: kubeops.dev
    app.kubernetes.io/component: panopticon
    app.kubernetes.io/part-of: opscenter-monitoring
spec:
  interval: 30m
  releaseName: panopticon
  chart:
    spec:
      chart: panopticon
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
