apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: panopticon
  namespace: kubeops
spec:
  interval: 30m
  releaseName: panopticon
  chart:
    spec:
      chart: panopticon
      targetNamespace: monitoring
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
