apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubestash-presets
  namespace: kubeops
  labels:
    ace.appscode.com/feature: kubestash-presets
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubestash-presets
  targetNamespace: kubestash
  storageNamespace: kubestash
  chart:
    spec:
      chart: kubestash-presets
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
