apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ui-server
  namespace: kubeops
  labels:
    app.kubernetes.io/managed-by: kubeops.dev
    app.kubernetes.io/component: kube-ui-server
    app.kubernetes.io/part-of: opscenter-core
spec:
  interval: 30m
  releaseName: kube-ui-server
  chart:
    spec:
      chart: kube-ui-server
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
