apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubestash
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubestash
  targetNamespace: kubestash
  storageNamespace: kubestash
  chart:
    spec:
      chart: kubestash
      version: "v2023.04.14"
      sourceRef:
        kind: HelmRepository
        name: kubestash
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    features:
      enterprise: true
