apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash-opscenter
  namespace: kubeops
  labels:
    ace.appscode.com/feature: stash-opscenter
spec:
  interval: 5m
  timeout: 30m
  releaseName: stash-opscenter
  targetNamespace: stash
  storageNamespace: stash
  chart:
    spec:
      chart: stash-opscenter
      version: "v2023.10.9"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    stash-metrics:
      enabled: false
