apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash-ui-server
  namespace: kubeops
spec:
  interval: 30m
  releaseName: stash-ui-server
  targetNamespace: stash
  chart:
    spec:
      chart: stash-ui-server
      version: "v2023.02.28"
      sourceRef:
        kind: HelmRepository
        name: stashed
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
