apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: mariadb-repo
  namespace: demo
  labels:
    app.kubernetes.io/name: mariadbs.kubedb.com
    app.kubernetes.io/instance: mariadb
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/mariadb/mariadb
    storageSecretName: gcs-secret
