apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: license-proxyserver
  namespace: kubeops
spec:
  interval: 30m
  releaseName: license-proxyserver
  targetNamespace: kubeops
  chart:
    spec:
      chart: license-proxyserver
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
