apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supervisor
  namespace: kubeops
spec:
  interval: 30m
  releaseName: supervisor
  chart:
    spec:
      chart: supervisor
      targetNamespace: kubeops
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
