apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supervisor
  namespace: kubeops
  labels:
    app.kubernetes.io/managed-by: kubeops.dev
    app.kubernetes.io/component: supervisor
    app.kubernetes.io/part-of: opscenter-essentials
spec:
  interval: 30m
  releaseName: supervisor
  chart:
    spec:
      chart: supervisor
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubeops
