apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco-ui-server
  namespace: kubeops
spec:
  interval: 5m
  timeout: 30m
  releaseName: falco-ui-server
  targetNamespace: falco
  storageNamespace: falco
  chart:
    spec:
      chart: falco-ui-server
      version: "v2023.03.23"
      sourceRef:
        kind: HelmRepository
        name: kubeops
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
