apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevault
  namespace: kubeops
spec:
  interval: 30m
  releaseName: kubevault
  targetNamespace: kubevault
  chart:
    spec:
      chart: kubevault
      version: "v2023.03.03"
      sourceRef:
        kind: HelmRepository
        name: kubevault
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
