apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scanner
  namespace: kubeops
spec:
  interval: 30m
  releaseName: scanner
  targetNamespace: kubeops
  chart:
    spec:
      chart: scanner
      version: "v2022.06.14"
      sourceRef:
        kind: HelmRepository
        name: kubeops
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
