apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  labels:
    app.kubernetes.io/instance: sample-mongo
    app.kubernetes.io/name: mongodbs.kubedb.com
  name: sample-mongo-restore
  namespace: demo
spec:
  repository:
    name: gcs-repo
  rules:
  - snapshots:
    - latest
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mongo
  task:
    name: mongodb-restore-4.2.3-v5
