apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: mongodb-repo
  namespace: demo
  labels:
    app.kubernetes.io/name: mongodbs.kubedb.com
    app.kubernetes.io/instance: mongodb
spec:
  backend:
    gcs:
      bucket: stash-testing
      prefix: /demo/mongodb
    storageSecretName: gcs-secret
