apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeform-provider-aws
  namespace: kubeops
  labels:
    ace.appscode.com/feature: kubeform-provider-aws
spec:
  interval: 5m
  timeout: 30m
  releaseName: kubeform-provider-aws
  targetNamespace: crossplane-system
  storageNamespace: crossplane-system
  chart:
    spec:
      chart: kubeform-provider-aws
      version: "v2023.11.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
