apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ui-server
  namespace: kubeops
  labels:
    app.kubernetes.io/component: kube-ui-server
spec:
  interval: 5m
  timeout: 30m
  releaseName: kube-ui-server
  targetNamespace: multicluster-controlplane
  storageNamespace: multicluster-controlplane
  chart:
    spec:
      chart: kube-ui-server
      version: "v2023.10.1"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  dependsOn:
    - name: multicluster-controlplane
  install:
    createNamespace: true
    crds: Skip
    remediation:
      retries: -1
  upgrade:
    crds: Skip
    remediation:
      retries: -1
  values:
    kubeconfigSecretName: multicluster-controlplane-svc-kubeconfig
