apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-snapshotter
  namespace: kubeops
  labels:
    app.kubernetes.io/component: external-snapshotter
spec:
  interval: 5m
  timeout: 30m
  releaseName: external-snapshotter
  targetNamespace: kubeops
  storageNamespace: kubeops
  chart:
    spec:
      chart: snapshot-controller
      version: "2.0.3"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
