apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: voyager-gateway
  namespace: kubeops
  labels:
    app.kubernetes.io/component: voyager-gateway
spec:
  interval: 5m
  timeout: 30m
  releaseName: voyager-gateway
  targetNamespace: gateway-system
  storageNamespace: gateway-system
  chart:
    spec:
      chart: gateway-helm
      version: "v0.0.0-latest"
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
