apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: voyager
  namespace: kubeops
  labels:
    ace.appscode.com/feature: voyager
spec:
  interval: 5m
  timeout: 30m
  releaseName: voyager
  targetNamespace: voyager
  storageNamespace: voyager
  chart:
    spec:
      chart: voyager
      version: v2023.9.18
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: kubeops
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
