apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
kind: Kustomization
patchesJson6902:
- path: patch.yaml
  target:
    group: kubedb.com
    kind: Elasticsearch
    name: elasticsearch
    namespace: demo
    version: v1alpha2
resources:
- elasticsearch-admin-cred.yaml
- elasticsearch-kibanaro-cred.yaml
- elasticsearch-kibanaserver-cred.yaml
- elasticsearch-logstash-cred.yaml
- elasticsearch-readall-cred.yaml
- elasticsearch-snapshotrestore-cred.yaml
